controller_manager:
  ros__parameters:
    update_rate: 100
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    joint_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    
    joint_position_controller:
      type: position_controllers/JointGroupPositionController
      
joint_velocity_controller:
  ros__parameters:
    joints:
      - base_rotater_joint
      - rotator_arm_joint
    command_interfaces:
      - velocity
    
joint_position_controller:
  ros__parameters:
    joints:
      - base_rotater_joint
      - rotator_arm_joint
    command_interfaces:
      - position 