controller_manager:
  ros__parameters:
    update_rate: 100
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
  
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController 
    
joint_trajectory_controller:
  ros__parameters:
    joints:
      - base_rotater_joint
      - rotator_arm_joint
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    action_monitor_rate: 20.0
    open_loop_control: true